# .drone.yml

kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

volumes:
  - name: deps
    temp: {}

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  volumes:
    - name: deps
      path: /go
  environment:
    GIT_PUSH_SSH_KEY:
      from_secret: git_push_ssh_key
  commands:
  - mkdir -p $HOME/.ssh
  - echo "$GIT_PUSH_SSH_KEY" > $HOME/.ssh/id_ed25519
  - chmod -R 700 $HOME/.ssh
  - ssh-keyscan source.symbolic.software > $HOME/.ssh/known_hosts
  - git clone git@source.symbolic.software:verifpal/verifpal.git .
  - git fetch --tags

- name: lint
  image: golangci/golangci-lint:latest
  commands:
    - make lint

- name: test
  image: golang:latest
  volumes:
    - name: deps
      path: /go
  commands:
    - make test

- name: release
  image: golang:latest
  volumes:
    - name: deps
      path: /go
  environment:
    GITEA_TOKEN:
      from_secret: gitea_token
    MAILGUN_TOKEN:
      from_secret: mailgun_token
  commands:
    - make release
  when:
    event: tag

- name: brew
  image: alpine/git
  volumes:
    - name: deps
      path: /go
  environment:
    GIT_PUSH_SSH_KEY:
      from_secret: git_push_ssh_key
  commands:
  - sh scripts/git.sh
  - git add HomebrewFormula/verifpal.rb
  - git commit -m "Update Homebrew formula"
  - git push
  when:
    event: tag