kind: pipeline
type: docker

steps:
- name: lint
  image: golangci/golangci-lint:latest
  commands:
  - golangci-lint run
- name: build
  image: golang:latest
  commands:
  - make dependencies
  - make parser
  - go version
  - go get ./...
  - go build verifpal.com/cmd/verifpal
- name: model
  image: golang:latest
  commands:
  - go run verifpal.com/cmd/verifpal verify examples/signal_small.vp
