---
kind: pipeline
type: docker
name: default

platform:
  arch: amd64
  os: linux

steps:
  - name: build
    image: golang:latest
    commands:
    - go get ./...
    - go build ./...
  - name: lint
    image: golangci/golangci-lint:latest
    commands:
    - golangci-lint run
  


