kind: pipeline
type: docker

steps:
- name: build
  image: golang:latest
  commands:
  - go version
  - make dependencies
  - make all
- name: lint
  image: golangci/golangci-lint:latest
  commands:
  - golangci-lint run