# .drone.yml

kind: pipeline
type: docker
name: linux-amd64

platform:
  os: linux
  arch: amd64

volumes:
  - name: deps
    temp: {}

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git config --global user.name "Drone"
  - git config --global user.email "drone@drone.symbolic.software"
  - git clone https://source.symbolic.software/verifpal/verifpal.git .
  - git fetch --tags

- name: lint
  image: golangci/golangci-lint:latest
  commands:
    - make lint

- name: test
  image: golang:latest
  volumes:
    - name: deps
      path: /go
  commands:
    - make test

- name: release
  image: golang:latest
  volumes:
    - name: deps
      path: /go
  environment:
    GITEA_TOKEN:
      from_secret: gitea_token
    MAILGUN_TOKEN:
      from_secret: mailgun_token
  commands:
    - make release
  when:
    event: tag

- name: brew
  image: appleboy/drone-git-push:latest
  volumes:
    - name: deps
      path: /go
  environment:
    GIT_PUSH_SSH_KEY:
      from_secret: git_push_ssh_key
  settings:
    author_name: drone
    author_email: drone@drone.symbolic.software
    remote: git@source.symbolic.software:verifpal/verifpal.git
    branch: master
    commit: true
    commit_message: Update Homebrew formula
  when:
    event: tag

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: golang:latest
  volumes:
    - name: deps
      path: /go
  commands:
    - make test

---
kind: pipeline
type: docker
name: windows-amd64

platform:
  os: windows
  arch: amd64

steps:
- name: test
  image: golang:latest
  volumes:
    - name: deps
      path: /go
  commands:
    - make test
