stages:
  - test
  - release

lint:
  image: golangci/golangci-lint:latest
  stage: test
  script:
    - golangci-lint run

test:
  image: golang:latest
  stage: test
  script:
    - make test

release:
  image: golang:latest
  stage: release
  only:
    - tags
  variables:
    GIT_DEPTH: 0
  script:
    - make release

snapcraft:
  image: ubuntu:18.04
  stage: release
  only:
    - tags
  script:
    - apt-get update -qy
    - apt-get install -y snapcraft 
    - echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
    - snapcraft login --with snapcraft.login
    - rm snapcraft.login
    - snapcraft
    - snapcraft push --release=stable *.snap
