stages:
  - lint
  - test

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  script:
    - make dep
    - make lint

test:
  image: golang:latest
  stage: test
  script:
    - make dep
    - make test

