stages:
  - test
  - release

lint:
  image: golang:latest
  stage: test
  script:
    - make lint

test:
  image: golang:latest
  stage: test
  script:
    - make test

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  variables:
    GORELEASER_IMAGE: goreleaser/goreleaser:latest
    DOCKER_REGISTRY: https://index.docker.io/v1/
    GIT_DEPTH: 0
  only:
    refs:
      - tags
  script: |
    docker pull $GORELEASER_IMAGE
    docker run --pull --rm --privileged \
      -v $PWD:/go/src/gitlab.com/symbolicsoft/verifpal \
      -w /go/src/gitlab.com/symbolicsoft/verifpal \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      $GORELEASER_IMAGE release --rm-dist