stages:
  - lint
  - test
  - snapcraft

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  script:
    - make dep
    - make lint

test:
  image: golang:latest
  stage: test
  script:
    - make dep
    - make test

snapcraft:
  image: ubuntu:18.04
  stage: snapcraft
  script:
    - apt-get update -qy
    - apt-get install -y snapcraft 
    - echo $SNAPCRAFT_LOGIN_FILE | base64 --decode > snapcraft.login
    - snapcraft login --with snapcraft.login
    - rm -f snapcraft.login *.snap
    - snapcraft
    - snapcraft push --release=stable *.snap
