stages:
  - test
  - release

lint:
  image: golangci/golangci-lint:latest
  stage: test
  script:
    - golangci-lint run

test:
  image: golang:latest
  stage: test
  script:
    - make test

release:
  image: docker:stable
  stage: release
  only:
    - tags
  services:
    - docker:dind
  variables:
    GORELEASER_IMAGE: goreleaser/goreleaser:latest
    DOCKER_REGISTRY: https://index.docker.io/v1/
    GIT_DEPTH: 0
  script: |
    docker pull $GORELEASER_IMAGE
    docker run --pull --rm --privileged \
      -v $PWD:/go/src/gitlab.com/symbolicsoft/verifpal \
      -w /go/src/gitlab.com/symbolicsoft/verifpal \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      $GORELEASER_IMAGE release --rm-dist

snapcraft:
  image: ubuntu:18.04
  stage: release
  only:
    - tags
  script:
    - apt-get update -qy
    - apt-get install -y snapcraft 
    - echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
    - snapcraft login --with snapcraft.login
    - snapcraft push --release=stable *.snap
  only:
    - master