project_name: verifpal

gitlab_urls:
  api: https://source.symbolic.software/api/v4/
  download: https://source.symbolic.software
  skip_tls_verify: false

before:
  hooks:
    - go generate ./...

builds:
  - main: ./cmd/verifpal/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE
      - examples/*
      - README.md
    wrap_in_directory: true

signs:
  - artifacts: checksum

changelog:
  skip: false
  sort: asc

release:
  gitlab:
    owner: verifpal
    name: verifpal

brews:
  - tap:
      owner: verifpal
      name: verifpal
    url_template: "https://source.symbolic.software/verifpal/verifpal/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
    commit_author:
      name: drone
      email: drone@symbolic.software
    folder: HomebrewFormula
    homepage: "https://verifpal.com"
    description: "Cryptographic protocol analysis for students and engineers."

scoop:
  bucket:
    owner: verifpal
    name: verifpal
  url_template: "https://source.symbolic.software/verifpal/verifpal/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
  commit_author:
    name: drone
    email: drone@symbolic.software
  homepage: "https://verifpal.com"
  description: "Cryptographic protocol analysis for students and engineers."
  license: "https://www.gnu.org/licenses/gpl-3.0.en.html"
