before:
  hooks:
    - go generate ./...
builds:
  - main: ./cmd/verifpal/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
archives:
- replacements:
    darwin: macos
  format: zip
  files:
    - LICENSES/*
    - examples/*
    - CHANGELOG.md
    - README.md
  wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
gitea_urls:
  api: https://source.symbolic.software/api/v1/
  skip_tls_verify: false
release:
  gitea:
    owner: nadim
    name: verifpal/verifpal
  disable: false
