# .goreleaser.yml

project_name: verifpal
before:
  hooks:
    - go generate ./...
builds:
  - main: ./cmd/verifpal/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
archives:
- replacements:
    darwin: macos
  format: zip
  files:
    - LICENSES/*
    - examples/*
    - README.md
  wrap_in_directory: true
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: false
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'typo'
    - '[CI SKIP]'
gitea_urls:
  api: https://source.symbolic.software/api/v1/
  skip_tls_verify: false
release:
  gitea:
    owner: verifpal
    name: verifpal
  name_template: "Verifpal {{.Version}}"
  prerelease: true
