project_name: verifpal

before:
  hooks:
    - go generate ./...

builds:
  - main: ./cmd/verifpal/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    files:
      - LICENSE
      - examples/*
      - README.md
    wrap_in_directory: true

changelog:
  skip: false
  sort: asc

release:
  github:
    owner: symbolicsoft
    name: verifpal

brews:
  - repository:
      owner: symbolicsoft
      name: verifpal
    commit_author:
      name: drone
      email: drone@symbolic.software
    folder: HomebrewFormula
    homepage: "https://verifpal.com"
    description: "Cryptographic protocol analysis for students and engineers."

scoops:
  - repository:
      owner: symbolicsoft
      name: verifpal
    commit_author:
      name: drone
      email: drone@symbolic.software
    homepage: "https://verifpal.com"
    description: "Cryptographic protocol analysis for students and engineers."
    license: "https://www.gnu.org/licenses/gpl-3.0.en.html"
