project_name: verifpal
before:
  hooks:
    - go generate ./...

builds:
  - main: ./cmd/verifpal/main.go
    gcflags:
      - -e
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
      - arm

archives:
  - replacements:
      darwin: macos
    format: zip
    files:
      - LICENSES/*
      - examples/*
      - README.md
    wrap_in_directory: true

changelog:
  skip: false
  sort: asc

release:
  gitlab:
    owner: symbolicsoft
    name: verifpal

brews:
  gitlab:
    owner: symbolicsoft
    name: verifpal
  commit_author:
    name: drone
    email: drone@symbolic.software
  folder: HomebrewFormula
  homepage: "https://verifpal.com"
  description: "Cryptographic protocol analysis for students and engineers."
  dependencies:
    - go
  install: |
    mkdir bin
		system "go", "build", "-trimpath", "-gcflags", "-e", "-ldflags", "-s -w", "-o", bin, "verifpal.com/cmd/..."
		prefix.install_metafiles
    
scoop:
  bucket:
    owner: symbolicsoft
    name: verifpal
  commit_author:
    name: drone
    email: drone@symbolic.software
  homepage: "https://verifpal.com"
  description: "Cryptographic protocol analysis for students and engineers."
  license: "https://www.gnu.org/licenses/gpl-3.0.en.html"