name: CI

on: [push, pull_request]

jobs:
  test:
    env:
      GOFLAGS: -buildvcs=fals
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v4.1.0
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: make dep
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.7.0
    - name: Run tests
      run: make test